export const manyFoodsStore = [
	{
		id: 1,
		title: 'Bananas',
		price: 48,
		description: 'Delicious and yellow',
		image: 'https://img.fozzyshop.com.ua/228783-thickbox_default/banani.jpg',
		available: 1,
	},
	{
		id: 2,
		title: 'Potatoes',
		price: 15,
		description: 'Real Ukrainian without parsley',
		image: 'https://img.fozzyshop.com.ua/58064-thickbox_default/kartofel-molodoj-ukraina.jpg',
		available: 1,
	},
	{
		id: 3,
		title: 'Cabbage',
		price: 88,
		description: 'Lots of green leaves',
		image: 'https://img.fozzyshop.com.ua/58048-thickbox_default/kapusta-rannyaya.jpg',
		available: 1,
	},
	{
		id: 4,
		title: 'Cucumbers',
		price: 89,
		description: 'The little green ones',
		image: 'https://img.fozzyshop.com.ua/57144-thickbox_default/ogurec-ekstra.jpg',
		available: 1,
	},
	{
		id: 5,
		title: 'Orange',
		price: 19,
		description: 'The juicy fruit of the wild',
		image: 'https://img.fozzyshop.com.ua/205216-thickbox_default/apelsin.jpg',
		available: 1,
	},
	{
		id: 6,
		title: 'Tomatoes',
		price: 88,
		description: 'Better cheap tomatoes than expensive watermelons',
		image: 'https://img.fozzyshop.com.ua/57218-thickbox_default/pomidor-koktejlnyj.jpg',
		available: 0,
	},
	{
		id: 7,
		title: 'Washed Beets',
		price: 64,
		description:
			'Washed with the tears of southern elephants under the glow of the full moon',
		image: 'https://img.fozzyshop.com.ua/19244-thickbox_default/svekla-mytaya.jpg',
		available: 0,
	},
	{
		id: 8,
		title: 'Dill fresh bunch',
		price: 40,
		description: "What's already there",
		image: 'https://img.fozzyshop.com.ua/11162-thickbox_default/ukrop-svezhij-puchek.jpg',
		available: 1,
	},
	{
		id: 9,
		title: 'Imported eggplant',
		price: 49,
		description: 'Beautiful eggplant, for your mom',
		image: 'https://img.fozzyshop.com.ua/57233-thickbox_default/baklazhan-importnij.jpg',
		available: 1,
	},
];
